### ISSUE TITLE
Buildbot

### ISSUE THREAD

**Issue by lgierth** [SeattleMeshnet/meshbox#24]
- [x] build cjdns and luci-app-cjdns packages
- [x] on master and for-14.07 commits
  - [x] development snapshots
  - [x] use openwrt trunk or 14.07, resp.
  - [x] build x86, preserving openwrt work directory
  - [x] run smoketest using docker container
- weekly using for-14.07
  - prebuilt firmware images for flashing
  - prebuilt packages for opkg repository and automatic updates
  - x86 smoketest
  - push docker image
  - build packages and firmware images
- netgear wnr2000v3 (this is the model that will be shipped)
- raspberry pi
- tp-link wdr4300
- beaglebone black

**Comment by lgierth** [comment]
So sorry, I totally forgot about the thread. You're correct, the smoketest builds an x86 image, establishes peering between two docker containers running the image, and then tries to ping each end.

We now build for a couple of targets: https://buildbot.meshwith.me/openwrt/builders, and all except the smoketest produce image and package snapshots: https://buildbot.meshwith.me/snapshots
I'm running these on ar71xx and oxnas devices, and hopefull soon on omap (Beaglebone Black).

The realview target is especially interesting, because it will hopefully allow us to run tests in QEMU (qemu-system-arm -M realview-eb-mpcore).

**Comment by lgierth** [comment]
We have a pretty good buildbot now, featuring the OpenWrt SDK and ImageBuilder, which cut the smoketest runtime down to 1 minute 43 seconds: http://buildbot.meshwith.me/openwrt/builders/cc-smoketest/builds/28

Regular packages and images are built even faster. The CPU and diskspace requirements are way smaller too. This means we can build on commodity hardware, and still expect fast results. The buildslaves should still be located on an SSD though.

Right now it builds packages for x86-generic and ar71xx-generic, and images for Docker and WNR2000v3. More targets will be added on demand.

**Comment by dangowrt** [comment]
I suggest we should build a hardened SDK for x86_64, realview and malta and use that for running the smoketest.
See https://gist.github.com/dangowrt/738c57a58e1f70a70ab5 to get an idea how this could work.
