### ISSUE TITLE
Get meshbox added to OpenWrt's feeds.conf.default

### ISSUE THREAD

**Issue by lgierth** [SeattleMeshnet/meshbox#37]

**Comment by dangowrt** [comment]
Nah, rather have cjdns merged into github.com/openwrt-routing or github.com/openwrt/packages. Let the luci add go upstream to LuCI like all other mesh-community stuff for now. If you need help in communicating additions towards upstream, I'd be happy to take that hat.

**Comment by lgierth** [comment]
I'd like to maintain our build infrastructure without building all of openwrt-routing, but I fear that moving the two packages to that feed might complicate this.

Do you think we could just do regular subtree merges of `meshbox.git/{cjdns,luci-app-cjdns}` to the feed, and maintain the meshbox feed as the master?
