### ISSUE TITLE
OpenWRT SSH didn't recognize the command "git" so I just unzipped the repository and...

### ISSUE THREAD

**Issue by PathosEthosLogos** [SeattleMeshnet/meshbox#41]
Hello,

I hope "help welcome" also means for the newbies.

I don't know how to use "git" command, so instead I extracted the zip file, but after that, I wasn't able to follow through the instructions, as I don't know where "openwrt" directory is. Please let me know!

Cheers

**Comment by lgierth** [comment]
Which step of the README instructions failed for you?

**Comment by wfleurant** [comment]
Please provide more information.
